[package]
name = "rust-project"
version = "0.0.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>", "Johnny Lin"]
description = "Shared project for learning Rust"
repository = "https://github.com/DoNotDoughnut/RustProject"
edition = "2018"
build = "build/build.rs"
readme = "README.md"

[dependencies]

macroquad = { git = "https://github.com/DoNotDoughnut/macroquad", default-features = false, features = ["log-impl", "text"] }
# nanoserde = "0.1.22" # Serialization and deserialization
# ahash = "0.7" # Faster hashmap
lazy_static = "1.4" # For global variables
# parking_lot = "0.11" # For faster Mutex and RwLock

#[target.'cfg(windows)'.build-dependencies]
#winres = "0.1.11"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
incremental = false # Prevents the saving of compile data to disk which speeds up the next compile (saves a lot of space)