[package]
name = "rust-project"
version = "0.0.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>", "Johnny Lin"]
description = "Shared project for learning Rust"
repository = "https://github.com/DoNotDoughnut/RustProject"
edition = "2018"

[dependencies]

# Game engine

macroquad = "0.3.0-alpha.14"

# Audio

# kira = "0.4.1"

# Other

# gilrs = "0.8" # Gamepad controls