[package]
name = "rust-project"
version = "0.0.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Game engine

piston_window = "0.117" # To-do: Use/create game engine that supports WebAssembly

# Other

enum-map = "0.6.4"
enum-iterator = "0.6.0"