[package]
name = "rust-project"
version = "0.0.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>", "Johnny Lin"]
description = "Shared project for learning Rust"
repository = "https://github.com/DoNotDoughnut/RustProject"
edition = "2018"
build = "build/build.rs"

[dependencies] # Kira and gilrs depend on a lot of stuff which will take up a lot of space 

# Game engine

macroquad = { git = "https://github.com/DoNotDoughnut/macroquad" }

# Audio

# kira = "0.4.1" # General audio manager

# Other

ahash = "0.7.0" # Faster hashmap
lazy_static = "1.4.0" # For the input hashmap
parking_lot = "0.11.1" # For faster mutex

# gilrs = "0.8" # Gamepad controls

#[target.'cfg(windows)'.build-dependencies]
#winres = "0.1.11"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3